<a href="https://colab.research.google.com/github/contandrey/ETL_dados_Resultados/blob/main/Desafiomodulo2_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# DESAFIO DO MÓDULO 2 - RESOLUÇÃO

#Importação dos pacotes

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from datetime import datetime

# Puxando o dataframe

In [ ]:
df = pd.read_csv("https://pycourse.s3.amazonaws.com/bike-sharing.csv")
df

,datetime,rec_id,season,year,month,hour,is_holiday,weekday,is_workingday,weather_condition,temp,atemp,humidity,windspeed,casual,registered,total_count
0,2011-01-01,1,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2011-01-01,2,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,2011-01-01,3,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,2011-01-01,4,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,2011-01-01,5,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,2012-12-31,17375,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17375,2012-12-31,17376,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17376,2012-12-31,17377,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17377,2012-12-31,17378,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61
17378,2012-12-31,17379,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

# exibindo o tamanho do dataset

In [ ]:
# exibindo o tamanho do dataset
tamanho = df.shape
print("tamanho do dataset:", tamanho)

tamanho do dataset: (17379, 18)



# Média das colunas windspeed e temp

In [ ]:
# qual a média da coluna windspeed?
df.groupby(by='windspeed') #agrupamento de valores utilizando um ou mais indices; o resultado exibido não tem valor aparentemente,
# porém tem que chamar outro método para soma, média, mediana etc, abaixo do resultado.

In [ ]:
#calculando a média da coluna windspeed
media = df['windspeed'].mean()
print(f"A média da coluna'windspeed' é:{media} ")

A média da coluna'windspeed' é:0.19009760630646177

In [ ]:
# Qual a média da coluna temp?
#calculando a média da coluna temp
media = df['temp'].mean()
print(f"A média da coluna'temp' é:{media} ")

A média da coluna'temp' é:0.4969871684216583

# Quantos registros em 2011

In [ ]:
#Quantos Registros existem para o ano de 2011?

df.dtypes #verificando o formato da coluna datetime, se for objeto o pandas não considera para operações, tem que transformar para dados.

datetime             datetime64[ns]
rec_id                        int64
season                       object
year                          int64
month                         int64
hour                 datetime64[ns]
is_holiday                    int64
weekday                       int64
is_workingday                 int64
weather_condition             int64
temp                        float64
atemp                       float64
humidity                    float64
windspeed                   float64
casual                        int64
registered                    int64
total_count                   int64
locacoes                      int64
dia_semana                   object
dtype: object

In [ ]:
#transformando a coluna datatime para dados
df['datetime'] = pd.to_datetime(df['datetime'])

In [ ]:
# Extração do ano
df['2011'] = df['datetime'].dt.year

In [ ]:
# Filtrar Ocorrências no ano desejado
ano_desejado = 2011
ocorrencias = df[df['2011'] == ano_desejado].shape[0]
print(f'O número de ocorrências em {ano_desejado} é: {ocorrencias}')

O número de ocorrências em 2011 é: 8645

# Quantos registros em 2012

In [ ]:
# Quantos registros existem para o ano de 2012?
# a coluna datetime já foi convertida para dados

# Extração do ano
df['2012'] = df['datetime'].dt.year

In [ ]:
# Filtro de ocorrências no ano desejado
ano_desejado = 2012
ocorrencias = df[df['2012'] == ano_desejado].shape[0]
print(f'O número de ocorrências em {ano_desejado} é: {ocorrencias}')

O número de ocorrências em 2012 é: 8734

# Quantas locações de bicicletas foram efetuadas em 2011?

In [ ]:
#casual: número de locações para usuários casuais;
#registered: número de locações para usuários registrados;
#total_count: contador total de aluguéis (casual+registered).

In [ ]:
#visualização das colunas
df.loc[:, ['datetime', 'casual', 'registered']]

        datetime  casual  registered
0     2011-01-01       3          13
1     2011-01-01       8          32
2     2011-01-01       5          27
3     2011-01-01       3          10
4     2011-01-01       0           1
...          ...     ...         ...
17374 2012-12-31      11         108
17375 2012-12-31       8          81
17376 2012-12-31       7          83
17377 2012-12-31      13          48
17378 2012-12-31      12          37

[17379 rows x 3 columns]

In [ ]:
# Extração do ano
df['2011'] = df['datetime'].dt.year
df['2012'] = df['datetime'].dt.year

In [ ]:
# Defina o ano específico que você deseja somar
ano_desejado = 2011

# Filtrar as linhas para o ano desejado
df_ano_especifico = df[df['datetime'].dt.year == ano_desejado]

# Somar os valores das colunas coluna1 e coluna2
soma_colunas = df_ano_especifico['casual'] + df_ano_especifico['registered']

# Obter a soma total
soma_total = soma_colunas.sum()

print(f'O total de locações em {ano_desejado} é: {soma_total}')

O total de locações em 2011 é: 1243103



# Quantas locações em 2012

In [ ]:
# Defina o ano específico que você deseja somar
ano_desejado = 2012

# Filtrar as linhas para o ano desejado
df_ano_especifico = df[df['datetime'].dt.year == ano_desejado]

# Somar os valores das colunas coluna1 e coluna2
soma_colunas = df_ano_especifico['casual'] + df_ano_especifico['registered']

# Obter a soma total
soma_total = soma_colunas.sum()

print(f'O total de locações em {ano_desejado} é: {soma_total}')

O total de locações em 2012 é: 2049576



# Qual estação do ano contém a maior média de locações de bicicletas?

In [ ]:
#season: estação do ano (1: inverno, 2: primavera, 3: verão, 4: outono)
# Suponha que você tenha um DataFrame chamado 'df' com uma coluna 'coluna_alvo' e uma coluna 'data'.

# Converta a coluna 'data' para o tipo datetime
df['datetime'] = pd.to_datetime(df['datetime'])

# Estamos criando uma nova coluna chamada "locacoes" - é soma das casuais e registradas
df['locacoes'] = df['casual'] + df['registered']

# Criando uma função para mapear as datas para estações do ano
def season_of_date(date):
    if date.month in [3, 4, 5]:
        return 'Primavera'
    elif date.month in [6, 7, 8]:
        return 'Verão'
    elif date.month in [9, 10, 11]:
        return 'Outono'
    else:
        return 'Inverno'

# Aplicando a função e criando uma nova coluna 'estacao'
df['season'] = df['datetime'].apply(season_of_date)

# Calculando a média de locações para cada estação
media_por_estacao = df.groupby('season')['locacoes'].mean().reset_index()

# Encontrando a estação com a maior média
estacao_maior_media = media_por_estacao.loc[media_por_estacao['locacoes'].idxmax()]

print("Estação com a maior média de locações:", estacao_maior_media['season'])
print("Média de locações:", estacao_maior_media['locacoes'])

Estação com a maior média de locações: Verão
Média de locações: 236.76674994322053

# Qual estação do ano contém a menor média de locações de bicicletas?

In [ ]:
# Suponha que você tenha um DataFrame chamado 'df' com as informações das locações e datas.
# Certifique-se de que a coluna 'data' seja do tipo datetime.
# Suponha também que a coluna de locações seja chamada 'locacoes'.

# Converta a coluna 'data' para o tipo datetime
df['datetime'] = pd.to_datetime(df['datetime'])

# Estamos criando uma nova coluna chamada "locacoes" - é soma das casuais e registradas
df['locacoes'] = df['casual'] + df['registered']

# Criando uma função para mapear as datas para estações do ano
def season_of_date(date):
    if date.month in [3, 4, 5]:
        return 'Primavera'
    elif date.month in [6, 7, 8]:
        return 'Verão'
    elif date.month in [9, 10, 11]:
        return 'Outono'
    else:
        return 'Inverno'

# Aplicando a função e criando uma nova coluna 'estacao'
df['season'] = df['datetime'].apply(season_of_date)

# Calculando a média de locações para cada estação
media_por_estacao = df.groupby('season')['locacoes'].mean().reset_index()

# Encontrando a estação com a menor média
estacao_menor_media = media_por_estacao.loc[media_por_estacao['locacoes'].idxmin()]

print("Estação com a menor média de locações:", estacao_menor_media['season'])
print("Média de locações:", estacao_menor_media['locacoes'])

Estação com a menor média de locações: Inverno
Média de locações: 116.9341641194451

# Qual horário do dia contém a maior média de locações de bicicletas?

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
#visualização das colunas
df.loc[:, ['datetime', 'hour', 'casual', 'registered']]

        datetime                          hour  casual  registered
0     2011-01-01 1970-01-01 00:00:00.000000000       3          13
1     2011-01-01 1970-01-01 00:00:00.000000001       8          32
2     2011-01-01 1970-01-01 00:00:00.000000002       5          27
3     2011-01-01 1970-01-01 00:00:00.000000003       3          10
4     2011-01-01 1970-01-01 00:00:00.000000004       0           1
...          ...                           ...     ...         ...
17374 2012-12-31 1970-01-01 00:00:00.000000019      11         108
17375 2012-12-31 1970-01-01 00:00:00.000000020       8          81
17376 2012-12-31 1970-01-01 00:00:00.000000021       7          83
17377 2012-12-31 1970-01-01 00:00:00.000000022      13          48
17378 2012-12-31 1970-01-01 00:00:00.000000023      12          37

[17379 rows x 4 columns]

In [ ]:
# Estamos criando uma nova coluna chamada "locacoes" - é soma das casuais e registradas
df['locacoes'] = df['casual'] + df['registered']

In [ ]:
##visualização das colunas
df.loc[:, ['datetime', 'hour', 'locacoes']]

         datetime  hour  locacoes
0      2011-01-01     0        16
1      2011-01-01     1        40
2      2011-01-01     2        32
3      2011-01-01     3        13
4      2011-01-01     4         1
...           ...   ...       ...
17374  2012-12-31    19       119
17375  2012-12-31    20        89
17376  2012-12-31    21        90
17377  2012-12-31    22        61
17378  2012-12-31    23        49

[17379 rows x 3 columns]

In [ ]:
#Converta a coluna "hour" para um formato de tempo (datetime) para facilitar o cálculo:
df['hour'] = pd.to_datetime(df['hour'])

# Primeiro, agrupe os dados pelo horário e calcule a média para cada horário
media_por_horario = df.groupby('hour')['locacoes'].mean()

# Em seguida, encontre o horário com a maior média
horario_maior_media = media_por_horario.idxmax()

# Agora você tem o horário com a menor média de dados
print("Horário com a maior média de dados:", horario_maior_media)

Horário com a maior média de dados: 1970-01-01 00:00:00.000000017

# Qual horário do dia contém a menor média de locações de bicicletas?

In [ ]:
# Estamos criando uma nova coluna chamada "locacoes" - é soma das casuais e registradas
df['locacoes'] = df['casual'] + df['registered']

In [ ]:
##visualização das colunas
df.loc[:, ['datetime', 'hour', 'locacoes']]

        datetime                          hour  locacoes
0     2011-01-01 1970-01-01 00:00:00.000000000        16
1     2011-01-01 1970-01-01 00:00:00.000000001        40
2     2011-01-01 1970-01-01 00:00:00.000000002        32
3     2011-01-01 1970-01-01 00:00:00.000000003        13
4     2011-01-01 1970-01-01 00:00:00.000000004         1
...          ...                           ...       ...
17374 2012-12-31 1970-01-01 00:00:00.000000019       119
17375 2012-12-31 1970-01-01 00:00:00.000000020        89
17376 2012-12-31 1970-01-01 00:00:00.000000021        90
17377 2012-12-31 1970-01-01 00:00:00.000000022        61
17378 2012-12-31 1970-01-01 00:00:00.000000023        49

[17379 rows x 3 columns]

In [ ]:
#Converta a coluna "hour" para um formato de tempo (datetime) para facilitar o cálculo:
df['hour'] = pd.to_datetime(df['hour'])

# Primeiro, agrupe os dados pelo horário e calcule a média para cada horário
media_por_horario = df.groupby('hour')['locacoes'].mean()

# Em seguida, encontre o horário com a menor média
horario_menor_media = media_por_horario.idxmin()

# Agora você tem o horário com a menor média de dados
print("Horário com a menor média de dados:", horario_menor_media)

Horário com a menor média de dados: 1970-01-01 00:00:00.000000004



# Que dia da semana da semana contém a maior media de locações de bicicletas?

In [ ]:
# Suponha que você tenha um DataFrame chamado df com colunas 'data' e 'locacoes'
# Substitua 'df' pelo nome do seu DataFrame, se necessário

# Certifique-se de que a coluna 'data' seja do tipo datetime
df['datetime'] = pd.to_datetime(df['datetime'])

# Extraia o dia da semana para cada data
df['dia_semana'] = df['datetime'].dt.day_name()

# Agrupe os dados pelo dia da semana e calcule a média de locações para cada dia
media_por_dia_semana = df.groupby('dia_semana')['locacoes'].mean()

# Encontre o dia da semana com a maior média de locações
dia_maior_media_locacoes = media_por_dia_semana.idxmax()

# Agora você tem o dia da semana com a maior média de locações
print("Dia da semana com a maior média de locações:", dia_maior_media_locacoes)

Dia da semana com a maior média de locações: Thursday

# Que dia da semana da semana contém a menor media de locações de bicicletas?

In [ ]:
# Suponha que você tenha um DataFrame chamado df com colunas 'data' e 'locacoes'
# Substitua 'df' pelo nome do seu DataFrame, se necessário

# Certifique-se de que a coluna 'data' seja do tipo datetime
df['datetime'] = pd.to_datetime(df['datetime'])

# Extraia o dia da semana para cada data
df['dia_semana'] = df['datetime'].dt.day_name()

# Agrupe os dados pelo dia da semana e calcule a média de locações para cada dia
media_por_dia_semana = df.groupby('dia_semana')['locacoes'].mean()

# Encontre o dia da semana com a menor média de locações
dia_menor_media_locacoes = media_por_dia_semana.idxmin()

# Agora você tem o dia da semana com a menor média de locações
print("Dia da semana com a menor média de locações:", dia_menor_media_locacoes)

Dia da semana com a menor média de locações: Sunday

# Às quartas-feiras qual horário com a maior media de locações?

In [ ]:
# weekday = 3 (quarta)

In [ ]:
# Suponha que você tenha um DataFrame chamado df com colunas 'data' e 'locacoes'
# Substitua 'df' pelo nome do seu DataFrame, se necessário

# Certifique-se de que a coluna 'data' seja do tipo datetime
df['datetime'] = pd.to_datetime(df['datetime'])

# Extraia o dia da semana para cada data
df['dia_semana'] = df['datetime'].dt.day_name()

# Filtra apenas as quartas-feiras
quartas_feiras = df[df['dia_semana'] == 'Wednesday']

# Agrupe os dados das quartas-feiras pelo horário e calcule a média de locações para cada horário
media_por_horario_quartas_feiras = quartas_feiras.groupby('hour')['locacoes'].mean()

# Encontre o horário com a maior média de locações nas quartas-feiras
horario_maior_media_quartas_feiras = media_por_horario_quartas_feiras.idxmax()

# Agora você tem o horário com a maior média de locações nas quartas-feiras
print("Horário com a maior média de locações nas quartas-feiras:", horario_maior_media_quartas_feiras)

Horário com a maior média de locações nas quartas-feiras: 1970-01-01 00:00:00.000000017

# horario com maior média de locações aos sábados

In [ ]:
# Suponha que você tenha um DataFrame chamado df com colunas 'data' e 'locacoes'
# Substitua 'df' pelo nome do seu DataFrame, se necessário

# Certifique-se de que a coluna 'data' seja do tipo datetime
df['datetime'] = pd.to_datetime(df['datetime'])

# Extraia o dia da semana para cada data
df['dia_semana'] = df['datetime'].dt.day_name()

# Filtra apenas os sábados
sabados = df[df['dia_semana'] == 'Saturday']

# Agrupe os dados dos sábados pelo horário e calcule a média de locações para cada horário
media_por_horario_sabados = sabados.groupby('hour')['locacoes'].mean()

# Encontre o horário com a maior média de locações nos sábados
horario_maior_media_sabados = media_por_horario_sabados.idxmax()

# Agora você tem o horário com a maior média de locações nos sábados
print("Horário com a maior média de locações nos sábados:", horario_maior_media_sabados)

Horário com a maior média de locações nos sábados: 1970-01-01 00:00:00.000000013